# Generated by Django 4.2.7 on 2025-12-24 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_alter_tenant_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExhibitionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Tag name", max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Tag color in hex format",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibition_tags",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exhibition Tag",
                "verbose_name_plural": "Exhibition Tags",
                "ordering": ["name"],
                "unique_together": {("name", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Exhibition name", max_length=200)),
                ("date", models.DateField(help_text="Date of the exhibition")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Exhibition description", null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Exhibition location",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active exhibitions are shown"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exhibitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exhibition tag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exhibitions",
                        to="exhibition.exhibitiontag",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibitions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exhibition",
                "verbose_name_plural": "Exhibitions",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
