# Generated by Django 4.2.7 on 2025-10-28 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_google_maps_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0002_alter_notification_type"),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle metadata field correctly
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="notification",
                    name="metadata",
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name='notifications_notification' 
                                AND column_name='metadata'
                            ) THEN
                                ALTER TABLE notifications_notification 
                                ADD COLUMN metadata JSONB DEFAULT '{}' NOT NULL;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        ALTER TABLE notifications_notification DROP COLUMN IF EXISTS metadata;
                    """,
                ),
            ],
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=500, unique=True)),
                ("p256dh", models.CharField(max_length=200)),
                ("auth", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="notificatio_user_id_d7f78b_idx"
                    ),
                    models.Index(
                        fields=["endpoint"], name="notificatio_endpoin_498a4c_idx"
                    ),
                ],
                "unique_together": {("user", "endpoint")},
            },
        ),
    ]
