# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telecalling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAssignmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('workload_balance', 'Workload Balance'), ('priority_based', 'Priority Based')], default='round_robin', max_length=50)),
                ('last_assigned_telecaller_id', models.IntegerField(blank=True, null=True)),
                ('assignment_count', models.IntegerField(default=0)),
                ('last_assignment_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_assignment_state',
            },
        ),
        migrations.CreateModel(
            name='TelecallerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=timezone.now)),
                ('leads_assigned', models.IntegerField(default=0)),
                ('calls_made', models.IntegerField(default=0)),
                ('calls_answered', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('avg_call_duration', models.FloatField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('telecaller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telecaller_performance',
                'unique_together': {('telecaller', 'date')},
            },
        ),
    ]
