# Generated by Django 4.2.7 on 2025-10-05 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telecalling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "webhook_type",
                    models.CharField(
                        choices=[
                            ("exotel", "Exotel"),
                            ("google_sheets", "Google Sheets"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["webhook_type", "status"],
                        name="telecalling_webhook_82c300_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="telecalling_created_c97b95_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("exhibition", "Exhibition"),
                            ("social_media", "Social Media"),
                            ("referral", "Referral"),
                            ("website", "Website"),
                            ("walk_in", "Walk In"),
                        ],
                        default="exhibition",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("appointment_set", "Appointment Set"),
                            ("not_interested", "Not Interested"),
                            ("converted", "Converted"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(default="google_sheets", max_length=50),
                ),
                ("source_id", models.CharField(max_length=100, unique=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("last_interaction", models.DateTimeField(blank=True, null=True)),
                ("next_followup", models.DateTimeField(blank=True, null=True)),
                ("call_attempts", models.IntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("segments", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FollowUpRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due_at", models.DateTimeField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reminder_enabled", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="telecalling.lead",
                    ),
                ),
                (
                    "telecaller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_at"],
            },
        ),
        migrations.CreateModel(
            name="CallRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[("outbound", "Outbound"), ("callback", "Callback")],
                        default="outbound",
                        max_length=20,
                    ),
                ),
                (
                    "exotel_call_sid",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("exotel_bridge_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("ringing", "Ringing"),
                            ("answered", "Answered"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("busy", "Busy"),
                            ("no_answer", "No Answer"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                ("recording_url", models.URLField(blank=True, null=True)),
                (
                    "disposition_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("follow_up_required", models.BooleanField(default=False)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_requests",
                        to="telecalling.lead",
                    ),
                ),
                (
                    "telecaller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CALL_INITIATED", "Call Initiated"),
                            ("CALL_COMPLETED", "Call Completed"),
                            ("CALL_FAILED", "Call Failed"),
                            ("LEAD_ASSIGNED", "Lead Assigned"),
                            ("LEAD_STATUS_UPDATED", "Lead Status Updated"),
                            ("FOLLOWUP_CREATED", "Follow-up Created"),
                            ("FOLLOWUP_COMPLETED", "Follow-up Completed"),
                            ("RECORDING_ACCESSED", "Recording Accessed"),
                            ("DATA_EXPORTED", "Data Exported"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("call", "Call"),
                            ("assignment", "Assignment"),
                            ("followup", "Follow-up"),
                            ("recording", "Recording"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_id", models.CharField(max_length=100)),
                ("metadata", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "assigned_to"], name="telecalling_status_fd1fc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["source", "status"], name="telecalling_source_191bc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["assigned_to", "status"], name="telecalling_assigne_b9937d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["next_followup"], name="telecalling_next_fo_f4fcd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="followuprequest",
            index=models.Index(
                fields=["lead", "status"], name="telecalling_lead_id_ab1976_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="followuprequest",
            index=models.Index(
                fields=["telecaller", "status"], name="telecalling_telecal_f5c2b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="followuprequest",
            index=models.Index(
                fields=["due_at", "status"], name="telecalling_due_at_b7bae6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrequest",
            index=models.Index(
                fields=["lead", "status"], name="telecalling_lead_id_1f7059_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrequest",
            index=models.Index(
                fields=["telecaller", "status"], name="telecalling_telecal_2d8aee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrequest",
            index=models.Index(
                fields=["exotel_call_sid"], name="telecalling_exotel__d548d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor", "timestamp"], name="telecalling_actor_i_fbdbd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="telecalling_target__5e9614_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="telecalling_action_5c29ae_idx"
            ),
        ),
    ]
