# Generated by Django 4.2.7 on 2025-10-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telecalling", "0002_alter_assignment_assigned_by_webhooklog_lead_and_more"),
    ]

    operations = []
