# Generated by Django 4.2.7 on 2025-10-05 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telecalling", "0003_add_new_telecalling_models"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="telecalling_actor_i_fbdbd9_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="telecalling_target__5e9614_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="telecalling_action_5c29ae_idx",
        ),
        migrations.RemoveIndex(
            model_name="callrequest",
            name="telecalling_lead_id_1f7059_idx",
        ),
        migrations.RemoveIndex(
            model_name="callrequest",
            name="telecalling_telecal_2d8aee_idx",
        ),
        migrations.RemoveIndex(
            model_name="callrequest",
            name="telecalling_exotel__d548d4_idx",
        ),
        migrations.RemoveIndex(
            model_name="followuprequest",
            name="telecalling_lead_id_ab1976_idx",
        ),
        migrations.RemoveIndex(
            model_name="followuprequest",
            name="telecalling_telecal_f5c2b9_idx",
        ),
        migrations.RemoveIndex(
            model_name="followuprequest",
            name="telecalling_due_at_b7bae6_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="telecalling_status_fd1fc0_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="telecalling_source_191bc2_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="telecalling_assigne_b9937d_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="telecalling_next_fo_f4fcd5_idx",
        ),
        migrations.RemoveIndex(
            model_name="webhooklog",
            name="telecalling_webhook_82c300_idx",
        ),
        migrations.RemoveIndex(
            model_name="webhooklog",
            name="telecalling_created_c97b95_idx",
        ),
        migrations.RenameField(
            model_name="callrequest",
            old_name="ended_at",
            new_name="answered_at",
        ),
        migrations.RenameField(
            model_name="callrequest",
            old_name="started_at",
            new_name="completed_at",
        ),
        migrations.RemoveField(
            model_name="callrequest",
            name="disposition_code",
        ),
        migrations.RemoveField(
            model_name="callrequest",
            name="exotel_bridge_url",
        ),
        migrations.RemoveField(
            model_name="callrequest",
            name="exotel_call_sid",
        ),
        migrations.RemoveField(
            model_name="callrequest",
            name="follow_up_required",
        ),
        migrations.RemoveField(
            model_name="followuprequest",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="followuprequest",
            name="reminder_enabled",
        ),
        migrations.AddField(
            model_name="callrequest",
            name="bridge_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="callrequest",
            name="disposition",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="callrequest",
            name="exotel_call_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="callrequest",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="target_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="callrequest",
            name="call_type",
            field=models.CharField(
                choices=[
                    ("outbound", "Outbound"),
                    ("followup", "Follow-up"),
                    ("callback", "Callback"),
                ],
                default="outbound",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="callrequest",
            name="recording_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="callrequest",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="callrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("queued", "Queued"),
                    ("ringing", "Ringing"),
                    ("answered", "Answered"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("busy", "Busy"),
                    ("no_answer", "No Answer"),
                ],
                default="initiated",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="followuprequest",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followup_requests",
                to="telecalling.lead",
            ),
        ),
        migrations.AlterField(
            model_name="followuprequest",
            name="telecaller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followup_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="fetched_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="lead",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="lead",
            name="segments",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("exhibition", "Exhibition"),
                    ("social_media", "Social Media"),
                    ("referral", "Referral"),
                    ("website", "Website"),
                    ("walk_in", "Walk In"),
                ],
                default="website",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
