# Generated by Django 4.2.7 on 2025-10-06 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telecalling", "0004_remove_auditlog_telecalling_actor_i_fbdbd9_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("new_uncontacted", "New / Uncontacted"),
                    ("attempted_contact", "Attempted Contact"),
                    ("missed_call_outbound", "Missed Call (Outbound)"),
                    ("missed_call_inbound", "Missed Call (Inbound)"),
                    ("contacted_in_progress", "Contacted / In Progress"),
                    ("follow_up_scheduled", "Follow-up Scheduled"),
                    ("interested_warm", "Interested / Warm"),
                    ("qualified", "Qualified"),
                    ("not_interested", "Not Interested"),
                    ("converted_closed_won", "Converted / Closed Won"),
                    ("lost_closed_lost", "Lost / Closed Lost"),
                ],
                default="new_uncontacted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LeadStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new_uncontacted", "New / Uncontacted"),
                            ("attempted_contact", "Attempted Contact"),
                            ("missed_call_outbound", "Missed Call (Outbound)"),
                            ("missed_call_inbound", "Missed Call (Inbound)"),
                            ("contacted_in_progress", "Contacted / In Progress"),
                            ("follow_up_scheduled", "Follow-up Scheduled"),
                            ("interested_warm", "Interested / Warm"),
                            ("qualified", "Qualified"),
                            ("not_interested", "Not Interested"),
                            ("converted_closed_won", "Converted / Closed Won"),
                            ("lost_closed_lost", "Lost / Closed Lost"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "call_duration",
                    models.IntegerField(
                        blank=True, help_text="Call duration in seconds", null=True
                    ),
                ),
                (
                    "call_outcome",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("next_action", models.TextField(blank=True, null=True)),
                ("next_action_date", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="telecalling.assignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Status History",
                "verbose_name_plural": "Lead Status Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
