# Generated by Django 4.2.7 on 2025-10-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telecalling", "0006_leadtransfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callrequest",
            name="bridge_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
