# Generated by Django 4.2.7 on 2025-10-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telecalling", "0002_leadassignmentstate_telecallerperformance"),
        ("telecalling", "0007_alter_callrequest_bridge_url"),
    ]

    operations = []
