# Generated by Django 4.2.7 on 2025-10-22 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telecalling", "0007_alter_callrequest_bridge_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_logs",
                to="telecalling.assignment",
            ),
        ),
        migrations.CreateModel(
            name="SimpleCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_phone", models.CharField(max_length=20)),
                (
                    "call_status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("no_answer", "No Answer"),
                            ("busy", "Busy"),
                            ("wrong_number", "Wrong Number"),
                            ("not_interested", "Not Interested"),
                            ("call_back", "Call Back Later"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "call_duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                (
                    "customer_sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("call_time", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telecaller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simple_call_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-call_time"],
            },
        ),
    ]
