// Mock data for tenant stores
import { Product, Category } from './api-service';

export const mockProducts: Record<string, Product[]> = {
  mandeep: [
    {
      id: 1,
      name: "Diamond Ring Collection",
      sku: "MANDEEP-DR-001",
      description: "Exquisite diamond ring with premium quality stones",
      category: 1,
      category_name: "Rings",
      brand: "Mandeep Jewelleries",
      cost_price: 50000,
      selling_price: 75000,
      discount_price: 65000,
      quantity: 10,
      min_quantity: 1,
      max_quantity: 5,
      weight: 5.2,
      dimensions: "18mm x 12mm",
      material: "18K Gold",
      color: "Yellow Gold",
      size: "18",
      status: "active",
      is_featured: true,
      is_bestseller: true,
      main_image: "/images/diamond-ring.jpg",
      additional_images: ["/images/diamond-ring-2.jpg", "/images/diamond-ring-3.jpg"],
      meta_title: "Diamond Ring Collection",
      meta_description: "Premium diamond rings by Mandeep Jewelleries",
      tags: ["diamond", "ring", "premium"],
      tenant: 1,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
      is_in_stock: true,
      is_low_stock: false,
      current_price: 65000,
      profit_margin: 30,
      variant_count: 3,
    },
    {
      id: 2,
      name: "Gold Necklace Set",
      sku: "MANDEEP-GN-002",
      description: "Traditional gold necklace set with matching earrings",
      category: 2,
      category_name: "Necklaces",
      brand: "Mandeep Jewelleries",
      cost_price: 80000,
      selling_price: 120000,
      discount_price: 110000,
      quantity: 5,
      min_quantity: 1,
      max_quantity: 3,
      weight: 25.5,
      dimensions: "24 inches",
      material: "22K Gold",
      color: "Yellow Gold",
      size: "24",
      status: "active",
      is_featured: true,
      is_bestseller: false,
      main_image: "/images/gold-necklace.jpg",
      additional_images: ["/images/gold-necklace-2.jpg"],
      meta_title: "Gold Necklace Set",
      meta_description: "Traditional gold necklace set",
      tags: ["gold", "necklace", "traditional"],
      tenant: 1,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
      is_in_stock: true,
      is_low_stock: false,
      current_price: 110000,
      profit_margin: 37.5,
      variant_count: 2,
    },
    {
      id: 3,
      name: "Pearl Earrings",
      sku: "MANDEEP-PE-003",
      description: "Elegant pearl earrings with diamond accents",
      category: 3,
      category_name: "Earrings",
      brand: "Mandeep Jewelleries",
      cost_price: 15000,
      selling_price: 25000,
      discount_price: 22000,
      quantity: 15,
      min_quantity: 1,
      max_quantity: 10,
      weight: 3.2,
      dimensions: "12mm x 8mm",
      material: "Sterling Silver",
      color: "White",
      size: "Standard",
      status: "active",
      is_featured: false,
      is_bestseller: true,
      main_image: "/images/pearl-earrings.jpg",
      additional_images: ["/images/pearl-earrings-2.jpg"],
      meta_title: "Pearl Earrings",
      meta_description: "Elegant pearl earrings",
      tags: ["pearl", "earrings", "elegant"],
      tenant: 1,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
      is_in_stock: true,
      is_low_stock: false,
      current_price: 22000,
      profit_margin: 46.7,
      variant_count: 4,
    },
  ],
  royal: [
    {
      id: 4,
      name: "Royal Diamond Crown",
      sku: "ROYAL-DC-001",
      description: "Luxury diamond crown for special occasions",
      category: 4,
      category_name: "Crowns",
      brand: "Royal Jewellers",
      cost_price: 200000,
      selling_price: 350000,
      discount_price: 320000,
      quantity: 2,
      min_quantity: 1,
      max_quantity: 1,
      weight: 45.0,
      dimensions: "Custom Size",
      material: "Platinum",
      color: "White",
      size: "Custom",
      status: "active",
      is_featured: true,
      is_bestseller: true,
      main_image: "/images/royal-crown.jpg",
      additional_images: ["/images/royal-crown-2.jpg"],
      meta_title: "Royal Diamond Crown",
      meta_description: "Luxury diamond crown",
      tags: ["crown", "luxury", "diamond"],
      tenant: 2,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
      is_in_stock: true,
      is_low_stock: true,
      current_price: 320000,
      profit_margin: 60,
      variant_count: 1,
    },
  ],
  diamond: [
    {
      id: 5,
      name: "Pure Diamond Solitaire",
      sku: "DIAMOND-PDS-001",
      description: "Pure diamond solitaire ring with exceptional clarity",
      category: 1,
      category_name: "Rings",
      brand: "Diamond Palace",
      cost_price: 150000,
      selling_price: 250000,
      discount_price: 230000,
      quantity: 8,
      min_quantity: 1,
      max_quantity: 2,
      weight: 8.5,
      dimensions: "20mm x 15mm",
      material: "18K White Gold",
      color: "White",
      size: "19",
      status: "active",
      is_featured: true,
      is_bestseller: true,
      main_image: "/images/diamond-solitaire.jpg",
      additional_images: ["/images/diamond-solitaire-2.jpg"],
      meta_title: "Pure Diamond Solitaire",
      meta_description: "Exceptional clarity diamond solitaire",
      tags: ["diamond", "solitaire", "pure"],
      tenant: 3,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
      is_in_stock: true,
      is_low_stock: false,
      current_price: 230000,
      profit_margin: 53.3,
      variant_count: 5,
    },
  ],
};

export const mockCategories: Record<string, Category[]> = {
  mandeep: [
    {
      id: 1,
      name: "Rings",
      description: "Exquisite ring collection",
      parent: null,
      tenant: 1,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: 2,
      name: "Necklaces",
      description: "Traditional necklace sets",
      parent: null,
      tenant: 1,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    {
      id: 3,
      name: "Earrings",
      description: "Elegant earring collection",
      parent: null,
      tenant: 1,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
  ],
  royal: [
    {
      id: 4,
      name: "Crowns",
      description: "Luxury crown collection",
      parent: null,
      tenant: 2,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
  ],
  diamond: [
    {
      id: 1,
      name: "Rings",
      description: "Premium diamond rings",
      parent: null,
      tenant: 3,
      is_active: true,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
  ],
};

export function getMockProducts(tenantId: string): Product[] {
  return mockProducts[tenantId] || [];
}

export function getMockCategories(tenantId: string): Category[] {
  return mockCategories[tenantId] || [];
} 