# Generated by Django 5.2.4 on 2025-08-22 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_populate_created_by'),
        ('tenants', '0002_tenant_google_maps_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(help_text='e.g., Gold, Silver, Diamond', max_length=100)),
                ('product', models.CharField(help_text='Specific product name', max_length=200)),
                ('revenue_opportunity', models.DecimalField(decimal_places=2, help_text='Estimated revenue opportunity', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this interest', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_interests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Customer Interest',
                'verbose_name_plural': 'Customer Interests',
                'ordering': ['-created_at'],
            },
        ),
    ]
