# Generated by Django 5.2.4 on 2025-08-22 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_add_customer_interest_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='next_follow_up_time',
            field=models.TimeField(blank=True, help_text='Time for next follow-up', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('wholesale', 'Wholesale')], default='individual', max_length=30),
        ),
    ]
