# Generated by Django 5.2.4 on 2025-08-22 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_add_missing_frontend_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='next_follow_up_time',
            field=models.CharField(blank=True, help_text='Time for next follow-up (HH:MM format)', max_length=10, null=True),
        ),
    ]
