# Generated by Django 5.2.4 on 2025-08-22 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_client_created_by_alter_client_next_follow_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinterest',
            name='main_category',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('diamond', 'Diamond'), ('platinum', 'Platinum'), ('pearl', 'Pearl'), ('ruby', 'Ruby'), ('emerald', 'Emerald'), ('sapphire', 'Sapphire'), ('other', 'Other')], help_text='e.g., Gold, Silver, Diamond', max_length=100),
        ),
    ]
