# Generated by Django 5.2.4 on 2025-08-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_client_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinterest',
            old_name='main_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='customerinterest',
            old_name='revenue_opportunity',
            new_name='revenue',
        ),
    ]
