# Generated by Django 5.2.4 on 2025-08-22 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20250822_2202'),
        ('products', '0003_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinterest',
            name='category',
            field=models.ForeignKey(help_text="Product category from tenant's catalog", on_delete=django.db.models.deletion.CASCADE, related_name='customer_interests', to='products.category'),
        ),
        migrations.AlterField(
            model_name='customerinterest',
            name='product',
            field=models.ForeignKey(help_text="Specific product from tenant's catalog", on_delete=django.db.models.deletion.CASCADE, related_name='customer_interests', to='products.product'),
        ),
    ]
