# Generated by Django 4.2.7 on 2025-08-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0025_add_exhibition_status"),
    ]

    operations = [
        # Client model indexes
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'is_deleted'], name='clients_cli_tenant_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email', 'tenant', 'is_deleted'], name='clients_cli_email_tenant_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone', 'tenant', 'is_deleted'], name='clients_cli_phone_tenant_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_cli_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_to'], name='clients_cli_assigned_to_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='clients_cli_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['next_follow_up'], name='clients_cli_next_follow_up_idx'),
        ),
        
        # Appointment model indexes
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'is_deleted'], name='clients_app_tenant_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'tenant'], name='clients_app_client_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='clients_app_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'status'], name='clients_app_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['assigned_to'], name='clients_app_assigned_to_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='clients_app_created_at_idx'),
        ),
        
        # FollowUp model indexes
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['tenant', 'is_deleted'], name='clients_fol_tenant_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['client', 'tenant'], name='clients_fol_client_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['due_date'], name='clients_fol_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['due_date', 'status'], name='clients_fol_due_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status'], name='clients_fol_status_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to'], name='clients_fol_assigned_to_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['created_at'], name='clients_fol_created_at_idx'),
        ),
        
        # ClientInteraction model indexes
        migrations.AddIndex(
            model_name='clientinteraction',
            index=models.Index(fields=['client'], name='clients_cli_inter_client_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinteraction',
            index=models.Index(fields=['interaction_type'], name='clients_cli_inter_type_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinteraction',
            index=models.Index(fields=['created_at'], name='clients_cli_inter_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinteraction',
            index=models.Index(fields=['follow_up_date'], name='clients_cli_inter_follow_up_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinteraction',
            index=models.Index(fields=['user'], name='clients_cli_inter_user_idx'),
        ),
        
        # CustomerTag model indexes
        migrations.AddIndex(
            model_name='customertag',
            index=models.Index(fields=['is_active'], name='clients_cust_tag_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customertag',
            index=models.Index(fields=['category'], name='clients_cust_tag_category_idx'),
        ),
        migrations.AddIndex(
            model_name='customertag',
            index=models.Index(fields=['category', 'is_active'], name='clients_cust_tag_cat_active_idx'),
        ),
    ]
