# Generated by Django 4.2.7 on 2025-10-10 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "clients",
            "0027_rename_clients_app_tenant_deleted_idx_clients_app_tenant__26dd72_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="add_to_pipeline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="checking_other_jewellers",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="customer_preferences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="customer_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="design_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="design_selected",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="diamond_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="gold_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="let_him_visit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="material_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="material_unit",
            field=models.CharField(blank=True, default="g", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="material_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="material_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="product_subtype",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="product_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="sales_person",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="sales_person_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="style",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="wants_more_discount",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
