# Generated by Django 4.2.7 on 2025-12-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0030_fix_email_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="area",
            field=models.CharField(
                blank=True,
                help_text="Locality/neighborhood within city",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="attended_by",
            field=models.CharField(
                blank=True,
                help_text="Sales representative who served the customer",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="client_category",
            field=models.CharField(
                blank=True,
                help_text="Customer category: Z Regular, Z Privilege, Z Loyal, Z Potential, etc.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="item_category",
            field=models.CharField(
                blank=True,
                help_text="Item category: 22ct Gold, 18ct Gold, Diamond, Villandi",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="item_name",
            field=models.CharField(
                blank=True,
                help_text="Product name: CHAIN, RING, SET-HALF, BRACELET, etc.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="preferred_flag",
            field=models.BooleanField(
                default=False, help_text="Preferred/VIP customer flag"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="sr_no",
            field=models.CharField(
                blank=True,
                help_text="Reference ID from import (e.g., ZJC12010)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="visit_date",
            field=models.DateField(
                blank=True, help_text="Date of customer visit/transaction", null=True
            ),
        ),
    ]
