# Generated by Django 4.2.7 on 2025-12-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0032_fix_preferred_flag_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="full_address",
            field=models.TextField(
                blank=True, help_text="Complete full address", null=True
            ),
        ),
    ]
