# Generated by Django 4.2.7 on 2025-12-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exhibition", "0001_add_exhibition_models"),
        ("clients", "0033_add_full_address_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="exhibition",
            field=models.ForeignKey(
                blank=True,
                help_text="Exhibition this lead was captured from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="exhibition.exhibition",
            ),
        ),
    ]
