# Generated by Django 4.2.7 on 2025-12-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_remove_salespipeline_sale"),
        ("clients", "0034_add_exhibition_field_to_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinterest",
            name="is_not_purchased",
            field=models.BooleanField(
                default=False,
                help_text="Whether customer explicitly didn't buy this product",
            ),
        ),
        migrations.AddField(
            model_name="customerinterest",
            name="is_purchased",
            field=models.BooleanField(
                default=False, help_text="Whether this interest was fulfilled/purchased"
            ),
        ),
        migrations.AddField(
            model_name="customerinterest",
            name="not_purchased_at",
            field=models.DateTimeField(
                blank=True, help_text="When customer decided not to buy", null=True
            ),
        ),
        migrations.AddField(
            model_name="customerinterest",
            name="purchased_at",
            field=models.DateTimeField(
                blank=True, help_text="When this product was purchased", null=True
            ),
        ),
        migrations.AddField(
            model_name="customerinterest",
            name="related_sale",
            field=models.ForeignKey(
                blank=True,
                help_text="Sale that fulfilled this interest",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_interests",
                to="sales.sale",
            ),
        ),
    ]
