# Generated by Django 4.2.7 on 2025-11-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_google_maps_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
