# Generated by Django 4.2.7 on 2025-10-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
    ]
