# Generated by Django 5.2.4 on 2025-08-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespipeline',
            name='stage',
            field=models.CharField(choices=[('exhibition', 'Exhibition'), ('social_media', 'Social Media'), ('interested', 'Interested'), ('store_walkin', 'Store - Walkin'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('future_prospect', 'Future Prospect'), ('not_qualified', 'Not Qualified')], default='exhibition', max_length=20),
        ),
    ]
