# Generated by Django 5.2.4 on 2025-08-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salespipeline_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespipeline',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_deals', to='sales.sale'),
        ),
    ]
