# Generated by Django 4.2.7 on 2025-10-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_salespipeline_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salespipeline",
            name="sale",
        ),
    ]
